# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.14,)" # Require at least 1.14.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="grayscalerpg"
version="${file.jarVersion}"
displayName="GrayScale RPG"
credits="Damoniy"
authors="Damoniy"
description='''
A magical adventure with fantasy elements.
'''
[[dependencies.grayscalerpg]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.grayscalerpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
